version: "3.7"

services:
  ui:
    container_name: react
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - "./front/ui/src:/app/src"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true