version: "3.7"

services:
  react:
    container_name: react
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - "./front/react/src:/app/src"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  nest:
    container_name: nest
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - "./back/nest/src:/nest/src"
    ports:
      - 8080:8080
